### PR TITLE
Geant4 formulas for RadLen and InterLen

### PR DESCRIPTION
**Pull request by petricm**
As discussed some time ago (AIDASoft/DD4hep#74), this is the my proposed addition to TGeo to fix the discrepancy between the ROOT formula for RadLen and the Geant4 one.

### CODE REVIEW

**Comment by agheata** [comment]
Hi Marco,
Apparently you forked from my branch which is very old and was not updated. You should rebase your branch on the master of ROOT's main repository. Here are some instructions (thanks to Guilherme Amadio) on how you can do this:

$ git remote add root-project git@github.com:root-project/root
$ git remote update
$ git rebase -i root-project/master <my local branch>

Then, when the editor comes up, delete all lines for commits you did not write yourself, if any, and if there are any conflicts, you'll have to resolve, do a git add on the conflicting file, then 
git rebase --continue 

Once that's finished, you can try:
$ git log --all --decorate --graph --oneline

and check that your branch shows up as branching from the
root-project/master branch, and only contains the commits that were
originally part of the branch before the rebase. For more info, check

https://root.cern.ch/creating-pull-request

Let me know if you need any more information.

**Comment by agheata** [comment]
... then close this pull request and make a new one...

**Comment by petricm** [comment]
Sorry I thought we agreed that I should PR you. My fork is from root-project and it is rebased on the root-project master. But if you want I can PR that.
However I did not implement how to switch between G3 and G4 formulas, as I thought this will be decided by you.

**Comment by petricm** [comment]
Closed by root-project/root#1184

**Pull request closed without merging**
